USE PRODDB
GO

SET NOCOUNT ON

SET QUOTED_IDENTIFIER ON
GO

DECLARE @GUID00 UNIQUEIDENTIFIER = (
	SELECT TOP (1) GUID00
	FROM Customers
	WHERE Name = '$(Name00)'
)
DECLARE @GUID01 UNIQUEIDENTIFIER = (
	SELECT TOP (1) GUID01
	FROM Brokers
	WHERE Name = '$(Name01)'
)

SELECT TOP (1)
	f.Mask [FileMask]
FROM [Configs] c
JOIN [Files] f WITH (NOLOCK) ON c.GUID02 = f.GUID02
WHERE
	f.TypeGUID IN (
		SELECT
			TypeGUID
		FROM Types WITH (NOLOCK)
		WHERE Name IN (
			'Accounts'
		)
	)
	AND c.GUID00 = @GUID00
	AND c.GUID01 = @GUID01